apiVersion: v1
kind: Service
metadata:
  name: addapi-service
spec:
  selector:
    app: addapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: subtractapi-service
spec:
  selector:
    app: subtractapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: calculator-loadbalancer
  labels: 
    app: calculatorapi
spec:
  type: LoadBalancer 
  selector:
    app: calculatorapi
  ports: 
    - port: 80
      targetPort: 80